name: ed_pyed
channels:
  - conda-forge
dependencies:
  - python=3.10
  - seaborn
  - numpy
  - scipy
  - pandas
  - matplotlib
  - tensorflow
  - joblib
  - scikit-learn
  - h5py
  - tqdm
  - jupyterlab
  - triqs
  - triqs_cthyb
  - ghostscript
  - cmake
